version: '3.8'

services:
  next-app:
    build: .
    container_name: next-app
    restart: always
    ports:
      - "3000:3000"
    networks:
      custom-net:
        ipv4_address: 172.20.0.20
    environment:
      - NODE_ENV=production

networks:
  custom-net:
    external: true
